### ISSUE TITLE
products handlers.go no such column: type

### ISSUE THREAD

**Issue by DankiCalamari** [wisepythagoras/pos-system#2]
when i try to create a product from the admin page i get 

```2023/07/28 04:00:16 /root/pos-system/product_handlers.go:120 no such column: type```

**Comment by wisepythagoras** [comment]
Will check it out!

**Comment by wisepythagoras** [comment]
@DankiCalamari pull, rebuild, and let me know if it's fixed for you

**Comment by DankiCalamari** [comment]
yeah its fixed for me. also I was wondering if I could distribute products with this software on it?

**Comment by wisepythagoras** [comment]
Could you expand? Do you mean ship tablets with the POS running on it?

**Comment by DankiCalamari** [comment]
Yeah

**Comment by DankiCalamari** [comment]
Like sell a pos with a local install of this pos software

**Comment by wisepythagoras** [comment]
@DankiCalamari, the current [license](https://github.com/wisepythagoras/pos-system/blob/main/LICENSE) permits commercial use, but if you need ongoing/priority support that'll be charged. Otherwise, releases/fixes will be made when I have the time to dedicate. It goes without saying, but contributing code changes are welcome.

**Comment by wisepythagoras** [comment]
Closing since the issue was fixed

**Comment by DankiCalamari** [comment]
ok cool
